### PR TITLE
fix: add missing exceptions to use cases

### LINKED ISSUE #51: Add missing exceptions
Since we did not know how to architecture our code, we did not have any exception. The goal of this ticket is to create all missing exceptions.

### PR DESCRIPTION
**Pull request by mikededo**
As explained in #51, there are use cases that do not have exceptions thrown because we did not know how to set up the folder structure, and, therefore, where to place the different exceptions.

Closes #51

### CODE REVIEW

**Review by sdomingobasora — APPROVED** [review]

File: src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromIdTest.java [hunk 1]
```diff
@@ -1,17 +1,20 @@
...
 import org.mockito.Mockito;
 
 import java.util.Optional;
 
-import static org.junit.jupiter.api.Assertions.assertFalse;
+import static org.junit.jupiter.api.Assertions.assertThrows;
 import static org.junit.jupiter.api.Assertions.assertTrue;
 
 public class GetOrganizationFromIdTest {
+    @SneakyThrows
```
Comment (manerow) [inline src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromIdTest.java:17]: Can we use the "throws" on the method signature instead of the @SneakyThrows lombok anotation? I find that explicitly declaring the different exceptions in the method signature is more self-documenting for the test case.

Comment (mikededo) [reply src/test/java/io/pakland/mdas/githubstats/domain/service/GetOrganizationFromIdTest.java:17]: Sure. Makes more sense. I opted for the `SneakyThrows` as it was the first thing suggested by the IDE.

**Review by manerow — APPROVED** [review]
